- name: Install OpenVPN and Easy-RSA
  ansible.builtin.apt:
    name:
      - openvpn
      - easy-rsa
    state: present

- name: Create Easy-RSA directory
  command: 
    cmd: make-cadir "{{ easy_rsa }}"
    creates: "{{ easy_rsa }}"
  
- name: Initialize PKI
  shell:
   ./easyrsa init-pki
  args:
    chdir: "{{ easy_rsa }}"
    creates: "{{ easy_rsa_pki }}"

- name: Create CA certificate
  shell:
    ./easyrsa build-ca nopass
  args:
    chdir: "{{ easy_rsa }}"
    creates: "{{ easy_rsa_pki }}/ca.crt"

- name: Generate server certificate request and sign it
  shell: 
    ./easyrsa gen-req server nopass
    echo "yes" | ./easyrsa sign-req server server
  args:
    chdir: "{{ easy_rsa }}"
    creates: "{{ easy_rsa_pki }}/issued/server.crt"

- name: Generate Diffie-Hellman parameters
  shell:
    ./easyrsa gen-dh
  args:
    chdir: "{{ easy_rsa }}"
    creates: "{{ easy_rsa_pki }}/dh.pem"

- name: Generate TLS-Auth key
  shell: 
    openvpn --genkey --secret pki/ta.key
  args:
    chdir: "{{ easy_rsa }}"
    creates: "{{ asy-rsa-pki }}/ta.key"

- name: Check OpenVPN directory
  file:
    path: /etc/openvpn
    state: directory
    mode: '0755'

- name: Copy OpenVPN files
  copy:
    src: "{{ item }}"
    dest: "{{ openvpn_conf_dir }}/"
    remote_src: yes
  with_items:
    - "{{ easy_rsa_pki }}/ca.crt"
    - "{{ easy_rsa_pki }}/issued/server.crt"
    - "{{ easy_rsa_pki }}/private/server.key"
    - "{{ easy_rsa_pki }}/dh.pem"
    - "{{ easy_rsa_pki }}/ta.key"

- name: Apply OpenVPN config
  template:
    src: "{{ openvpn_server_conf }}"
    dest: /etc/openvpn/server.conf

- name: Start OpenVPN server
  systemd:
    name: openvpn@server
    state: started
    enabled: yes

- name: Create client config
  template:
    src: "{{ openvpn_server_conf }}"
    dest: "client.ovpn"